# Dockerfile to create Mageia linux cauldron base images
# Create base image with mkimage-urpmi.sh script
#

FROM scratch
MAINTAINER "Juan Luis Baptiste" <juancho@mageia.org> - ./mkimage-urpmi.sh
ADD rootfs.tar.xz /
